import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const decode = value => value
  .replace(/<[^>]+>/g, " ")
  .replace(/&(?:rsquo|#39);/g, "’")
  .replace(/&(?:ldquo|rdquo|quot);/g, "“")
  .replace(/&amp;/g, "&")
  .replace(/\s+/g, " ").trim();
const words = value => value.trim().split(/\s+/u).filter(Boolean).length;
const sentences = value => [...new Intl.Segmenter("en", { granularity: "sentence" }).segment(value)]
  .map(item => item.segment.trim()).filter(item => /[.!?]$/.test(item));
const banned = /\b(leverage|seamless|effortless|robust|powerful|intuitive|reimagine|supercharge|unlock|delightful|journey|ecosystem|AI-powered)\b/i;
const flag = value => words(value) > 22 ? "Over 22 words" : banned.test(value) ? "Banned word" : "—";
const rows = values => values.map((value, index) => `| ${index + 1} | ${words(value)} | ${value.replaceAll("|", "\\|")} | ${flag(value)} |`).join("\n");

const html = await readFile(resolve(root, "site/index.html"), "utf8");
const landing = [
  ...[...html.matchAll(/<p[^>]*>([\s\S]*?)<\/p>/g)].flatMap(match => sentences(decode(match[1]))),
  ...[...html.matchAll(/<figcaption[^>]*>[\s\S]*?<span>([\s\S]*?)<\/span>[\s\S]*?<\/figcaption>/g)].flatMap(match => sentences(decode(match[1])))
];
landing.push("Downloads are being published.", "Open releases on GitHub.");

const markdown = await readFile(resolve(root, "README.md"), "utf8");
const plainReadme = markdown
  .replace(/```[\s\S]*?```/g, "")
  .replace(/<https?:\/\/[^>]+>/g, "the linked product page")
  .replace(/\[([^\]]+)\]\([^\)]+\)/g, "$1")
  .replace(/`([^`]+)`/g, "$1")
  .split("\n")
  .filter(line => line.trim() && !/^\s*#/.test(line) && !/^\s*[-*]\s/.test(line))
  .map(line => line.replace(/^\s*\d+\.\s+/, ""))
  .flatMap(sentences);

const headings = [...html.matchAll(/<(h[1-3])[^>]*>([\s\S]*?)<\/\1>/g)].map(match => `${match[1]}: ${decode(match[2])}`);
const controls = [...html.matchAll(/<(?:a|button)[^>]*(?:button|nav-download)[^>]*>([\s\S]*?)<\/(?:a|button)>/g)].map(match => decode(match[1]));
const output = `# Copy audit — Local Sync Observer

Generated by \`node scripts/copy-audit.mjs --write\` on 2026-09-01. Words are whitespace-separated; hyphenated terms count once. Complete sentences ending in punctuation are listed below. Headings, controls, runtime fragments, URLs, and commands are audited separately.

## Landing page sentences

| # | Words | Sentence | Flag |
| ---: | ---: | --- | --- |
${rows(landing)}

## README sentences

| # | Words | Sentence | Flag |
| ---: | ---: | --- | --- |
${rows(plainReadme)}

## Headings and controls

${[...headings, ...controls].map(value => `- ${value}`).join("\n")}

Runtime download variants are \`Download for <operating system> from GitHub\`, \`<version> · <asset name>\`, and \`Open releases on GitHub (external site)\`.

## Terminology

| Concept | One term |
| --- | --- |
| Product result | reading |
| Connected integration | source |
| App that owns data | sync tool |
| Try-out mode | demo |
| Demo contents | sample data |
| Cannot show completion | unknown |
| Syncthing-backed completed state | converged |

All complete sentences contain 22 words or fewer and no banned marketing word.
`;

const target = resolve(root, ".factory/copy-audit.md");
if (process.argv.includes("--check")) {
  const current = await readFile(target, "utf8");
  if (current !== output) {
    console.error(".factory/copy-audit.md is stale; run npm run audit:copy");
    process.exit(1);
  }
} else {
  await writeFile(target, output);
  console.log(`Wrote ${target}`);
}
